### ISSUE TITLE
Unable to retrieve redis client from store

### ISSUE THREAD

**Issue by lays147** [node-cache-manager/node-cache-manager-redis-yet#165]
Hello! I'm using this lib as store of Cache Manager in a NestJS app.

I'm trying to close the connection to the redis instance using the `onModuleDestroy` function, however, the redis client is unavailable when I try to access the client, as you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/7799231/218211650-26d05294-221e-4234-a0fb-d702049aacd0.png)

I can see in your tests that the client should be available after accessing the `store` attribute, but in my case is not. Is there anything that I need to do to be able to access the client?

**Comment by botika** [comment]
```typescript
constructor(@Inject(CACHE_MANAGER) private cacheManager: RedisCache) {}
```
