### ISSUE TITLE
How to wrap a function that might return null

### ISSUE THREAD

**Issue by paulwellnerbou** [node-cache-manager/node-cache-manager-redis-yet#270]
When using redis-yet as cache and wrap a function that might return null, I get following error (if it returns null):

```
NoCacheableError {
  message: '"null" is not a cacheable value',
  name: 'NoCacheableError'
}
```

This does not happen if I am using memory cache with `node-cache-manager`.

My code:

```
return cache.wrap(key, fn, ttl); // fn is a function returning a value or null
```

How am I supposed to handle those cases? Catch the exception and go on? Or is there a way to add a callback that checks if the result value should be cached?

**Comment by botika** [comment]
https://github.com/node-cache-manager/node-cache-manager-redis-yet/blob/28dea659f731cb81a80e449e84dd2118072596ad/src/index.ts#L58-L59

Not pass null value to cache or use other `isCacheable` callback.

**Comment by paulwellnerbou** [comment]
I have no influence in the return value in this case.

I will try the `isCacheable` option, this sounds good. Thank you!

But there seem to be already code for exactly the same problem:

```
export const avoidNoCacheable = async <T>(p: Promise<T>) => {
  try {
    return await p;
  } catch (e) {
    if (!(e instanceof NoCacheableError)) throw e;
  }
};
```

For now, I did the same thing.

**Comment by botika** [comment]
ok, thx!
