### ISSUE TITLE
Is this package stable? 

### ISSUE THREAD

**Issue by marcosmartinez7** [node-cache-manager/node-cache-manager-redis-yet#304]
Hello, 

We are trying to add Redis cache to our Nest.js backend. 

Taking a look to the Nest.js documentation (https://docs.nestjs.com/techniques/caching) it has a link to https://github.com/dabroek/node-cache-manager-redis-store 

I found that this project is a fork of `node-cache-manager-redis-store` and we have some questions: 

1. is this project stable? is the right way to implement Redis into nest? or is under project and we should use `Ioredis` or `node-redid`? 
2. what about `node-cache-manager-redis-store`, is deprecated? 

Thanks in advance

**Comment by botika** [comment]
The nestjs documentation is wrong on that part. It is stable and the one that has to be used. 

Do not forget not to come on vacation to Spain, it is impossible to buy or rent a house near my family thanks to mass tourism. :smiley: Thank you.
