### ISSUE TITLE
JSON.parse() error

### ISSUE THREAD

**Issue by little-yellow-bean** [node-cache-manager/node-cache-manager-redis-yet#391]
If the value in redis is a simple text type, then when getting the value out will throw "Uncaught SyntaxError: Unexpected token xxx".

**Comment by pixeldin** [comment]
@little-yellow-bean I got the same problem now, can you pls show me about how to solve it?

**Comment by pixeldin** [comment]
> @little-yellow-bean I got the same problem now, can you pls show me about how to solve it?

I just upgrade redis server's version from `3.0`+ to `5.0`+ and solve it.

**Comment by pixeldin** [comment]
@little-yellow-bean I made a mistake, this problem is still not solved.
My redis-server : `Redis 5.0.14.1 64 bit`

Node dependencies:
```
"cache-manager": "^5.2.4",
"cache-manager-redis-store": "^3.0.1",
```
Config template:
```
import { ConfigModule, ConfigService } from '@nestjs/config';
import { redisStore } from 'cache-manager-redis-store';
@Module({
  imports: [
    CacheModule.registerAsync({
      isGlobal: true,
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async () => {
        const store = await redisStore({
          socket: {
            host: process.env.REDIS_HOST,
            // @ts-ignore
            port: process.env.REDIS_PORT,
          },
          // @ts-ignore
          database: process.env.REDIS_DB,
          password: process.env.REDIS_PASSWORD,
          ttl: 100,
        });
        return {
          store: store as unknown as CacheStore,
        };
      },
    }),
  ],
  providers: [RedisService],
  exports: [RedisService],
})
export class RedisModule {}
```
I got some err when I try to get a string key:
> \cache-manager-redis-store\dist\index.js:832
  return JSON.parse(val);
              ^
SyntaxError: Unexpected token p in JSON at position 0
    at JSON.parse (<anonymous>)
    at decodeValue (F:\Project\xxx\node_modules\cache-manager-redis-store\dist\index.js:83
2:15)
    at _callee2$ (F:\Project\xxx\node_modules\cache-manager-redis-store\dist\index.js:513:
75)
Do you have any ideas to solve it?

**Comment by little-yellow-bean** [comment]
> @little-yellow-bean I made a mistake, this problem is still not solved. My redis-server : `Redis 5.0.14.1 64 bit`
> 
> Node dependencies:
> 
> ```
> "cache-manager": "^5.2.4",
> "cache-manager-redis-store": "^3.0.1",
> ```
> 
> Config template:
> 
> ```
> import { ConfigModule, ConfigService } from '@nestjs/config';
> import { redisStore } from 'cache-manager-redis-store';
> @Module({
>   imports: [
>     CacheModule.registerAsync({
>       isGlobal: true,
>       imports: [ConfigModule],
>       inject: [ConfigService],
>       useFactory: async () => {
>         const store = await redisStore({
>           socket: {
>             host: process.env.REDIS_HOST,
>             // @ts-ignore
>             port: process.env.REDIS_PORT,
>           },
>           // @ts-ignore
>           database: process.env.REDIS_DB,
>           password: process.env.REDIS_PASSWORD,
>           ttl: 100,
>         });
>         return {
>           store: store as unknown as CacheStore,
>         };
>       },
>     }),
>   ],
>   providers: [RedisService],
>   exports: [RedisService],
> })
> export class RedisModule {}
> ```
> 
> I got some err when I try to get a string key:
> 
> > \cache-manager-redis-store\dist\index.js:832
> > return JSON.parse(val);
> > ^
> > SyntaxError: Unexpected token p in JSON at position 0
> > at JSON.parse ()
> > at decodeValue (F:\Project\xxx\node_modules\cache-manager-redis-store\dist\index.js:83
> > 2:15)
> > at _callee2$ (F:\Project\xxx\node_modules\cache-manager-redis-store\dist\index.js:513:75)
> 
> Do you have any ideas to solve it?

did you set the value into Redis by this lib or manually? My case is because I manually set the value into Redis without quotation marks.

**Comment by pixeldin** [comment]
> > @little-yellow-bean I made a mistake, this problem is still not solved. My redis-server : `Redis 5.0.14.1 64 bit`
> > Node dependencies:
> > ```
> > "cache-manager": "^5.2.4",
> > "cache-manager-redis-store": "^3.0.1",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Config template:
> > ```
> > import { ConfigModule, ConfigService } from '@nestjs/config';
> > import { redisStore } from 'cache-manager-redis-store';
> > @Module({
> >   imports: [
> >     CacheModule.registerAsync({
> >       isGlobal: true,
> >       imports: [ConfigModule],
> >       inject: [ConfigService],
> >       useFactory: async () => {
> >         const store = await redisStore({
> >           socket: {
> >             host: process.env.REDIS_HOST,
> >             // @ts-ignore
> >             port: process.env.REDIS_PORT,
> >           },
> >           // @ts-ignore
> >           database: process.env.REDIS_DB,
> >           password: process.env.REDIS_PASSWORD,
> >           ttl: 100,
> >         });
> >         return {
> >           store: store as unknown as CacheStore,
> >         };
> >       },
> >     }),
> >   ],
> >   providers: [RedisService],
> >   exports: [RedisService],
> > })
> > export class RedisModule {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I got some err when I try to get a string key:
> > > \cache-manager-redis-store\dist\index.js:832
> > > return JSON.parse(val);
> > > ^
> > > SyntaxError: Unexpected token p in JSON at position 0
> > > at JSON.parse ()
> > > at decodeValue (F:\Project\xxx\node_modules\cache-manager-redis-store\dist\index.js:83
> > > 2:15)
> > > at _callee2$ (F:\Project\xxx\node_modules\cache-manager-redis-store\dist\index.js:513:75)
> > 
> > 
> > Do you have any ideas to solve it?
> 
> did you set the value into Redis by this lib or manually? My case is because I manually set the value into Redis without quotation marks.

In fact, I found that the `set()` and `get()` operation functions can only operate on strings with json format, otherwise the regular string type will report a json parsing error, that's strange
![image](https://github.com/node-cache-manager/node-cache-manager-redis-yet/assets/16974018/c560f8ae-ed6f-4c65-bc45-99f564dd3318)
![image](https://github.com/node-cache-manager/node-cache-manager-redis-yet/assets/16974018/4c1eb337-be2c-4007-b09e-6ca9b7f99604)
Maybe I need to look into the internal implementation details.
![image](https://github.com/node-cache-manager/node-cache-manager-redis-yet/assets/16974018/5de4ffc6-2839-4967-9d47-144fdad3218f)

**Comment by little-yellow-bean** [comment]
> [pixeldin](/pixeldin)

hmm, it should work for both because it's doing JSON.stringify() when setting the value in then do JSON.parse() when getting the value out, if it successfully sets the value then it shouldn't get a parsing error when getting it out. I still suspect it is because the value you are trying to get out was not set by this lib (because in your first screenshot the "pig" should be "\"pig\"" I think, correct me if Im wrong).

**Comment by pixeldin** [comment]
> > [pixeldin](/pixeldin)
> 
> hmm, it should work for both because it's doing JSON.stringify() when setting the value in then do JSON.parse() when getting the value out, if it successfully sets the value then it shouldn't get a parsing error when getting it out. I still suspect it is because the value you are trying to get out was not set by this lib (because in your first screenshot the "pig" should be "\"pig\"" with back slashes escaping I think, if you set the value in terminal manually you need to do: `set pixel "\"pig\""` , correct me if Im wrong).
----
@little-yellow-bean, thanks for your reply. It works with this `set pixel "\"pig\""`, but I still don't know why the quotes are needed before getting.
I try the `set()` function with the lib before the `get()` func:
![image](https://github.com/node-cache-manager/node-cache-manager-redis-yet/assets/16974018/e1bcb242-f877-4961-9ea9-7fb245f0afcc)
![image](https://github.com/node-cache-manager/node-cache-manager-redis-yet/assets/16974018/19329a33-b8f0-4e75-ad6d-19ed1800f966)
now I got another problem :(
![image](https://github.com/node-cache-manager/node-cache-manager-redis-yet/assets/16974018/9bc8294f-d2cf-4f58-818c-536825a6b731)
