### ISSUE TITLE
Incompatible with NestJS cache store

### ISSUE THREAD

**Issue by cristian-moreno-ruiz** [node-cache-manager/node-cache-manager-redis-yet#394]
I have recently upgraded my Nestjs, cache-manager, cache-manager-redis-store, etc dependencies in my project, and I stumbled with an issue that was previously reported in the original package this repository has been forked from, this is the original issue:

https://github.com/dabroek/node-cache-manager-redis-store/issues/53

So after finding out that package is kind of abandoned and this one is a fork and it is maintained, I wanted to pop this up here, since I am facing the same problem in this package, this is the way I'm trying to register the cache module:

```
import * as redisStore from 'cache-manager-redis-yet';
````

...

```
CacheModule.register({
    isGlobal: true,
    store: redisStore,
    url: "redis://localhost:6379",
}),
```
And the Type error is:

```
Types of property 'store' are incompatible. 
Type 'typeof import("/node_modules/cache-manager-redis-yet/dist/index")' is not assignable to type 'string | CacheStoreFactory | CacheStore'.ts(2322)
cache-module.interface.d.ts(12, 5): The expected type comes from property 'useFactory' which is declared here on type 'CacheModuleAsyncOptions<{ store: typeof import("/node_modules/cache-manager-redis-yet/dist/index"); url: string; }>'
```

And also, for anyone facing this issue, I'm currently using a solution I found in that other repository, which is to use `require` in this way:
```
const redisStore = require('cache-manager-redis-yet').redisStore;
```

Which is not ideal but at least it works.

Thanks in advance for your help!

**Comment by hankyupark** [comment]
try this.
```
import { redisStore } from 'cache-manager-redis-yet';
```

**Comment by cristian-moreno-ruiz** [comment]
I'd had bet I had tried tis before posting here, but I believe I may have tried with the other package. Thanks for letting me know, works perfect!
